apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: ehr-transcript-consolidation-service
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: <mysql-root-password>
  MYSQL_USER: <mysql-user-name>
  MYSQL_PASSWORD: <mysql-user-password>
  MYSQL_HOST: mysql-service
  MYSQL_PORT: "3306"
  MYSQL_DATABASE: application_db