apiVersion: apps/v1
kind: Deployment
metadata: 
  name: frontend-deployment
  namespace: ehr-transcript-consolidation-service
  labels:
    app.kubernetes.io/name: frontend-deployment
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: ehr-transcript-consolidation-service

spec: # Deployment specification
  replicas: 1
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 300
  minReadySeconds: 10

  strategy:
    type: RollingUpdate # default
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%

  selector:
    matchLabels:
      app.kubernetes.io/name: frontend-pod
      app.kubernetes.io/component: frontend

  template: # Pod template 
    metadata: # Pod metadata
      labels:
        app.kubernetes.io/name: frontend-pod
        app.kubernetes.io/component: frontend

    spec: # Pod specification
      containers:
      - name: frontend
        image: frontend
        imagePullPolicy: Never # default

        ports:
        - name: http
          containerPort: 3000
          protocol: TCP

        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"

        env:
        - name: API_BASE_URL
          value: http://api:8080
